[package]
name = "alloye"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A blazingly fast rust web framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
